# Generated by Django 4.2.16 on 2024-10-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='简述')),
                ('count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('text', models.TextField(blank=True, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '花语内容',
                'verbose_name_plural': '花语内容',
                'db_table': 'tb_content',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('url', models.CharField(max_length=300, null=True, verbose_name='内容链接')),
            ],
            options={
                'verbose_name': '滑动幻灯片',
                'verbose_name_plural': '滑动幻灯片',
                'db_table': 'tb_slide',
            },
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='图片')),
                ('good_id', models.CharField(max_length=100, null=True, verbose_name='商品id')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.content', verbose_name='contents')),
            ],
            options={
                'verbose_name': '花语图片管理',
                'verbose_name_plural': '花语图片管理',
                'db_table': 'tb_content_image',
            },
        ),
    ]
